Update patch set 6
Patch Set 6:

FYI: This breaks the build in packages/services/Telecomm/tests

ERROR: packages/services/Telecomm/tests/src/com/android/server/telecom/tests/CallAudioModeStateMachineTest.java:107: The constructor CallAudioModeStateMachine(AudioManager) is undefined
ERROR: packages/services/Telecomm/tests/src/com/android/server/telecom/tests/CallAudioModeStateMachineTest.java:546: The constructor CallAudioModeStateMachine(AudioManager) is undefined

Patch-set: 6