Update patch set 1
Patch Set 1:

> results in a soft reboot when i try to call someone.
 > with this patch, dialer crashes because it can not look up
 > IExtTelephony$Stub

i mean with this patch, it does not soft reboot anymore but crashes the dialer.

if i switch dialer to static telephony-ext it goes further, asks which sim i want to use for calling and crashes then, because of a NPE


java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.codeaurora.internal.IExtTelephony.isLocalEmergencyNumber(java.lang.String)' on a null object reference

Patch-set: 1