Update patch set 3
Patch Set 3: Code-Review-1

09-11 20:22:39.878   783  3179 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Binder:783_B
09-11 20:22:39.878   783  3179 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/i18n/phonenumbers/PhoneNumberUtil;
09-11 20:22:39.878   783  3179 E AndroidRuntime: 	at org.lineageos.internal.telephony.SensitivePhoneNumbers.formatNumberToNational(SensitivePhoneNumbers.java:149)
09-11 20:22:39.878   783  3179 E AndroidRuntime: 	at org.lineageos.internal.telephony.SensitivePhoneNumbers.isSensitiveNumber(SensitivePhoneNumbers.java:107)
09-11 20:22:39.878   783  3179 E AndroidRuntime: 	at com.android.server.telecom.CallLogManager.logCall(CallLogManager.java:304)
09-11 20:22:39.878   783  3179 E AndroidRuntime: 	at com.android.server.telecom.CallLogManager.logCall(CallLogManager.java:249)
09-11 20:22:39.878   783  3179 E AndroidRuntime: 	at com.android.server.telecom.CallLogManager.logCall(CallLogManager.java:204)
09-11 20:22:39.878   783  3179 E AndroidRuntime: 	at com.android.server.telecom.CallLogManager.onCallStateChanged(CallLogManager.java:189)
09-11 20:22:39.878   783  3179 E AndroidRuntime: 	at com.android.server.telecom.CallsManager.setCallState(CallsManager.java:2498)
09-11 20:22:39.878   783  3179 E AndroidRuntime: 	at com.android.server.telecom.CallsManager.markCallAsDisconnected(CallsManager.java:2004)
09-11 20:22:39.878   783  3179 E AndroidRuntime: 	at com.android.server.telecom.ConnectionServiceWrapper$Adapter.setDisconnected(ConnectionServiceWrapper.java:224)
09-11 20:22:39.878   783  3179 E AndroidRuntime: 	at com.android.internal.telecom.IConnectionServiceAdapter$Stub.onTransact(IConnectionServiceAdapter.java:161)
09-11 20:22:39.878   783  3179 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:731)
09-11 20:22:39.878   783  3179 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.i18n.phonenumbers.PhoneNumberUtil" on path: DexPathList[[zip file "/system/priv-app/Telecom/Telecom.apk"],nativeLibraryDirectories=[/system/priv-app/Telecom/lib/arm64, /system/priv-app/Telecom/Telecom.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64, /system/lib64, /system/vendor/lib64]]
09-11 20:22:39.878   783  3179 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
09-11 20:22:39.878   783  3179 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
09-11 20:22:39.878   783  3179 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)


Anyone any idea? without the "dontwarn" in the proguard i couldn't make it compile, now it doesn't warn but crashes the system

Patch-set: 3
Reviewer: Gerrit User 11883 <11883@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Reviewer: Gerrit User 8461 <8461@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Reviewer: Gerrit User 13028 <13028@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Code-Review=-1